Introduce roundcube_working_dir variable.
systemli/ansible-role-roundcube pull request #40
Opened 2023-04-17 15:15 UTC by neidiom

My Control Panel by default sets the user home dir to a different location than `roundcube_user_home` so every time I run this role it sets it to `roundcube_user_home` and then the Control Panel changes it back. This PR fixes this.

2023-04-17 15:20 UTC, doobry-systemli requested changes

2023-04-17 15:20 UTC, doobry-systemli commented on defaults/main.yml
> +roundcube_user_home_directory: "/var/www/{{ roundcube_domain }}"
I think this approach is a bit confusing for people who don't face the issues you face. Maybe instead we could introduce a `roundcube_home` variable that defaults to `"{{ roundcube_user_home }}` and use that variable everywhere except for the task that creates the user? What do you think @t2d?

2023-04-17 19:23 UTC, t2d commented
The naming of the variables is definitely confusing. But I also don't get the problem. 
@neidiom you should adjust `roundcube_user_home` to the one provided by your control panel. Then you should set `roundcube_path` to the directory where you want to install roundcube. Shouldn't that be enough?

2023-04-17 21:34 UTC, neidiom commented
@t2d I tried that before and it does not work. The role breaks. I am using ISPConfig which uses sym links for the web folder as following

`Website path - /var/www/clients/client[client_id]/web[website_id]`
`Website symlinks - /var/www/[website_domain]/:/var/www/clients/client[client_id]/[website_domain]/`

The `Website path` has special permissions via `chattr` so no new files can be created outside the web directory.

2023-04-17 21:36 UTC, neidiom commented
But I agree that the variable naming is confusing. Maybe instead of `roundcube_user_home_directory` I change it to `system_user_home_directory` @t2d ?

2023-04-17 21:39 UTC, neidiom commented
So in my example the links are set as this

````
lrwxrwxrwx 1 root root 31 Apr 12 06:23 /var/www/xxx.mydomain.com -> /var/www/clients/client1/web17/
````

````
# ls -al /var/www/xxx.mydomain.com/web/ | grep www
lrwxrwxrwx  1 web17     client1        66 Apr 17 18:06 www -> /var/www/clients/client1/web17/web/roundcubemail-1.6.1/public_html
````

2023-04-17 21:48 UTC, neidiom commented
Also the Control Panel has `open_basedir` restrictions set so the files need to be inside the web folder.

```
grep open /etc/php/8.1/fpm/pool.d/web17.conf 
php_admin_value[open_basedir] = /var/www/clients/client1/web17/web:/var/www/clients/client1/web17/private:/var/www/clients/client1/web17/tmp
```

2023-04-17 21:58 UTC, neidiom commented
@t2d I changed the name of the variable so that it id less confusing.

2023-04-18 05:26 UTC, t2d commented
Thanks for you work on this. However, due to ansible convention every variable must start with `roundcube_`. Please go the other way around. `roundcube_user_home` should define the home of the roundcube user. But you can add another variable e.g. `roundcube_working_dir` with default `roundcube_working_dir = {{ roundcube_user_home }}` and then override these variables in your case. Do you understand what I mean?

2023-04-18 06:16 UTC, neidiom commented
@t2d Please review the changes.

2023-04-18 13:44 UTC, t2d commented
Great, exactly what I imagined.

2023-04-18 13:44 UTC, merged